// curricula/btech/ai-6.js
// B.Tech CSE – Artificial Intelligence · Semester 6 (Year 3)
// AY: batch_year + 2  →  e.g. 2024 batch = AY 2026-27
// Last synced: April 2026

export const AI_6 = {
  key: 'AI-6',
  label: 'Sem 6 — CSE Artificial Intelligence',
  branch: 'B.Tech CSE - Artificial Intelligence',
  shortBranch: 'CSE Artificial Intelligence',
  program: 'btech',
  year: 3,
  sem: 6,
  subjects: [
    {
      name: 'Project - 1',
      code: '303105300',
      credits: 3,
      type: 'lab',
      units: [
        'Introductory Guidelines — General Instructions on Project Definition, Different Platforms, Planning the Programme',
        'Analysis — Deep Study about Project Title, Available System, User Requirements',
        'Design — Designing Architecture & System from Requirements Gathered in Analysis',
        'Implementation — Implement the Design Work',
        'Testing — Implement Different Test Cases for the Project',
        'Documentation — Project Report, Seminar & Poster Presentation',
      ],
    },
    {
      name: 'Compiler Design',
      code: '303105350',
      credits: 3,
      type: 'theory',
      units: [
        'Overview of Compilation & Lexical Analysis — Compiler Structure & Applications, Role of Lexical Analyzer, Specification & Recognition of Tokens, LEX Tool & Example Programs',
        'Syntax Analysis — Role of Parser, Context-Free Grammars (CFG), Techniques for Writing Grammars, Left Recursion Removal, Non-Context-Free Constructs, Parse Trees & Ambiguity',
        'Top-Down Parsing — FIRST & FOLLOW Sets, LL(1) Conditions, Predictive Parsing, Recursive Descent Parsing, Error Recovery',
        'Bottom-Up (LR) Parsing — Handle Pruning, Shift-Reduce Parsing, Viable Prefixes, LR(0) Automaton, LR-Parsing Algorithm, SLR(1), LR(1), LALR(1)',
        'YACC — YACC Specifications, Error Recovery with YACC, Examples of YACC Programs',
        'Syntax-Directed Definitions — Attribute Grammars, Synthesized & Inherited Attributes, Evaluation Orders, Dependency Graphs, S-Attributed & L-Attributed SDDs',
        'Semantic Analysis — Symbol Tables & Data Structures, Scope Representation, Expressions, Assignment & Control-Flow Statements, Function Declarations & Calls, Semantic Error Recovery',
        'Intermediate Code Generation — Quadruples, Triples, Trees, Flow Graphs, SSA Forms, Expression Translation, Control-Flow Statements, Boolean Expressions, Back Patching',
        'Run-Time Environments — Stack Allocation, Activation Records, Access to Non-Local Data, Procedures with & without Nesting',
        'Machine Code Generation & Optimization — Simple Machine Code Generation, Machine-Independent Code Optimizations',
      ],
    },
    {
      name: 'Compiler Design Laboratory',
      code: '303105350L',
      credits: 1,
      type: 'lab',
      units: [
        'Lexical Analysis in C — Lexical Analyzer Implementation, Count Digits/Vowels/Symbols, Username & Password Validation',
        'Parsing in C — LL(1) Predictive Parsing, Recursive Descent Parsing, Operator Precedence Parsing, LALR Parsing',
        'LEX Programs — Character/Line/Word Counter from File, Vowel & Consonant Counter, Number Extractor, HTML Tag Extractor, Line Numbering Program',
      ],
    },
    {
      name: 'Machine Learning',
      code: '303105353',
      credits: 3,
      type: 'theory',
      units: [
        'Introduction to ML — Learning Paradigms, PAC Learning, Basics of Probability, Version Spaces',
        'ML in Practice — Data Collection, Preprocessing (Missing Values, Normalization), Outlier Analysis (Z-Score), Model Selection & Evaluation, Hyperparameter Tuning, Result Visualization',
        'Supervised Learning I — Linear & Non-Linear Examples, Multi-Class & Multi-Label Classification, Linear Regression, Multilinear Regression, Naïve Bayes Classifier, Decision Trees (ID3, CART), Error Bounds',
        'Supervised Learning II — K-NN Classifier, Logistic Regression, Perceptrons (Single & Multi-layer), Support Vector Machines (Linear & Non-linear), Semi-Supervised Learning',
        'Unsupervised Learning — Clustering (Partitioned, Hierarchical, Density-Based), K-Means, K-Mode, Self-Organizing Maps, Expectation Maximization, PCA, Reinforcement Learning',
        'Evaluation Metrics & Ensemble Learning — ROC Curves, Significance Tests, Error Correction in Perceptrons, Bagging, Boosting, Random Forests, AdaBoost, XGBoost',
      ],
    },
    {
      name: 'ML Laboratory',
      code: '303105354',
      credits: 1,
      type: 'lab',
      units: [
        'Data Handling — NumPy, Pandas, Statistics Library, Diwali Sales Dataset Analysis & Visualization',
        'Supervised Learning — Linear Regression, Logistic Regression, Naïve Bayes Classifier (CSV), Decision Tree ID3, KNN (Iris Dataset), SVM Comparison',
        'Unsupervised & Advanced — K-Means Clustering, EM Algorithm, Bayesian Network (Heart Disease Dataset), Unsupervised Comparison (K-Means vs K-Mode), ANN with Backpropagation',
      ],
    },
    {
      name: 'High Performance Computing',
      code: '303105356',
      credits: 3,
      type: 'theory',
      units: [
        'Introduction to Parallel Computing — Motivating Parallelism, Scope, Parallel Programming Platforms, Implicit Parallelism, Trends in Microprocessor Architectures, Memory System Limitations',
        'Parallel Platform Models — Levels of Parallelism (Instruction/Transaction/Task/Thread/Memory/Function), SIMD/MIMD/SIMT/SPMD, N-wide Superscalar, Multi-core, Multi-threaded',
        'Parallel Algorithm Design — Decomposition Techniques, Task & Interaction Characteristics, Load Balancing, Interaction Overhead, Parallel Algorithm Models',
        'Message-Passing (MPI) — Principles of Message-Passing, Send & Receive Operations, MPI Interface, Topology & Embedding, Communication with Computation, Collective Communication',
        'Synchronization & OpenMP — Scheduling, Job Allocation, Thread Basics, POSIX Pthreads API, Thread Creation/Termination, Synchronization Primitives, OpenMP Directive-Based Parallel Programming',
        'GPGPU & CUDA — Overview of GPGPU, DGX Architecture, GPGPU Programming, GPGPU Memory Hierarchy, CUDA Programming Basics',
        "Performance Measures — Speedup, Efficiency, Scalability, Abstract Performance Metrics (Work, Critical Paths), Amdahl's Law, Granularity & Real Performance",
      ],
    },
    {
      name: 'HPC Laboratory',
      code: '303105356L',
      credits: 1,
      type: 'lab',
      units: [
        'Setup & Linux — Google Colab Facilities, Basic Linux Commands, Task Distribution using Gprof',
        'Parallel Programming — Concurrent QuickSort using Divide & Conquer (C++), MPI Functions Demo, OpenMP & Pthreads Demonstration',
        'CUDA Programming — Hello World CUDA, Add Two Numbers CUDA, Add Two Arrays CUDA, Code Analysis with Nvidia-Profilers',
      ],
    },
    {
      name: 'Employability Skills',
      code: '303193353',
      credits: 1,
      type: 'soft',
      units: [
        'IELTS Mock Test — Developing English Learning, Employment Prospects, Practice on Listening, Speaking, Reading & Writing',
        'Resume Building — Cover Letter & Resume Writing, Creating Functional Resume for Job/College/Scholarship Applications',
        'Advanced Group Discussion — Mock GD Round, Training in Interpersonal Skills, Generating New Ideas, Problem-Solving Approaches',
        'Personal Interview — Mock Interview, Preparing for Interview, Review Questions, Employer\'s Expectations, Case Interview',
      ],
    },
    {
      name: 'MEA(R)N Stack Web Development',
      code: '303105385',
      credits: 3,
      type: 'theory',
      units: [
        'Introduction to MEAN Stack — Overview of Web Development, Introduction to MEAN Stack, Setting up the Development Environment',
        'MongoDB — Introduction to NoSQL Databases, Installation & Configuration, CRUD Operations, Indexing & Querying, Schema Design & Data Modeling',
        'Node.js & Express.js — Introduction to Node.js & Express.js, Middleware & Routing, Authentication & Security with Passport.js, Error Handling & Logging',
        'Angular — Introduction, Setting up Angular App, Components, Modules & Services, Data Binding & Templates, Forms & Validation, Routing & Navigation, HTTP & Observables',
        'Integration & Deployment — Angular Frontend with Express.js API, Authentication & User Management, WebSockets for Real-Time Data, Error Handling & Testing, Hosting, Security Best Practices, Performance, Version Control & CI',
        'Final Project — Full-Stack MEAN Application Development',
      ],
    },
    {
      name: 'MEAN Stack Laboratory',
      code: '303105386',
      credits: 1,
      type: 'lab',
      units: [
        'Setup & Overview — Introduction to MEAN Stack, Development Environment Setup, Overview of MongoDB, Express.js, Angular & Node.js',
        'Backend Development — Creating & Configuring MongoDB, Creating & Configuring Express.js, Building RESTful APIs with Express.js',
        'Frontend Development — Introduction to Angular, Building Basic UI Components, Creating Single-Page Application (SPA)',
        'Server-Side Development — Introduction to Node.js, Creating & Configuring Node.js, Building Server-Side Applications',
        'Integration & Deployment — Integrating All Components, Testing & Debugging the Full-Stack Application, Deploying on Cloud Platform',
      ],
    },
    {
      name: 'Cybersecurity',
      code: '303105341',
      credits: 3,
      type: 'theory',
      units: [
        'Information Security — Introduction to Information Systems, Types, Development, Introduction to InfoSec, Need for Security, Threats to Information Systems, CIA Triad, Security Risk Analysis',
        'Systems Vulnerability Scanning — Vulnerability Scanning Overview, Port/Service Identification, Banner/Version Check, Traffic & Vulnerability Probes, Netcat, Port & Services Tools, Nmap Reconnaissance, Wireshark',
        'Network Defense Tools — Firewall Basics, Packet Filter vs Firewall, Stateless vs Stateful Firewalls, NAT & Port Forwarding, VPN Basics, Linux Firewall, Windows Firewall, Snort IDS',
        'Cyber Crime & Law — Cybercrime Types, Hacking, Attack Vectors, Cyberspace & Criminal Behavior, Incident Response, Digital Forensics, History of Internet, IT Act 2000',
        'Cyber Crime Investigation — Password Cracking, Key Loggers & Spyware, Virus & Worms, Trojans & Backdoors, Steganography, DoS & DDoS Attacks, SQL Injection, Buffer Overflow, Wireless Network Attacks',
      ],
    },
    {
      name: 'Cybersecurity Laboratory',
      code: '303105342',
      credits: 1,
      type: 'lab',
      units: [
        'Reconnaissance — Gathering Information using Whois, Port Scanners, Network Scanning, Angry IP Scanner',
        'Firewall & Proxy — Experiments with Open Source Firewall/Proxy (iptables, squid)',
        'Attack Techniques — Implementation of Steganography, MITM Attack using Wireshark/Network Sniffers, Windows Security using Firewalls',
        'Web Vulnerability — Identify Web Vulnerabilities using OWASP Project',
        'Digital Forensics — IT Audit, Malware Analysis, Vulnerability Assessment & Report, OS Hardening, RAM Dump Analysis, Mobile Audit, Cyber Forensics Tools (Disk Imaging, Data Acquisition & Recovery)',
      ],
    },
  ],
};
