// curricula/btech/aids-4.js
// B.Tech CSE – AI & Data Science · Semester 4 (Year 2)
// AY: batch_year + 1  →  e.g. 2024 batch = AY 2025-26
// Last synced: April 2026

export const AIDS_4 = {
  key: 'AIDS-4',
  label: 'Sem 4 — AI & Data Science',
  branch: 'B.Tech CSE - AI & Data Science',
  shortBranch: 'CSE AI & Data Science',
  program: 'btech',
  year: 2,
  sem: 4,
  subjects: [
    {
      name: 'Operating System',
      code: '303105251',
      credits: 3,
      type: 'theory',
      units: [
        'Introduction to OS — Concept, Generations, Types of OS, OS Services, System Calls, Layered/Monolithic/Microkernel Structure, Virtual Machine',
        'Processes & Threads — Process Definition, States & Transitions, PCB, Context Switching, Thread Types & States, Benefits of Multithreading',
        'Process Scheduling — Scheduling Objectives, Types of Schedulers, Scheduling Criteria (CPU Utilization, Throughput, Turnaround Time), FCFS, SJF, Round Robin',
        'Inter-Process Communication — Critical Section, Race Conditions, Mutual Exclusion, Semaphores, Monitors, Message Passing, Reader-Writer Problem, Dining Philosopher Problem',
        "Deadlocks — Necessary & Sufficient Conditions, Prevention, Avoidance (Banker's Algorithm), Deadlock Detection & Recovery",
        'Memory Management — Contiguous Allocation, Fixed & Variable Partition, Internal & External Fragmentation, Paging, Hardware Support, Advantages & Disadvantages',
        'Virtual Memory — Basics, Hardware & Control Structures, Locality of Reference, Page Fault, Demand Paging, Page Replacement (Optimal/FIFO/LRU/NRU/SC)',
        'I/O & File Systems — I/O Hardware, Device Controllers, DMA, Interrupt Handlers, Device Drivers, File Concepts, Access Methods, Allocation Methods, Disk Scheduling (FCFS/SSTF/SCAN/C-SCAN)',
      ],
    },
    {
      name: 'OS Laboratory',
      code: '303105252',
      credits: 1,
      type: 'lab',
      units: [
        'Linux & Shell Scripting — Basic Linux Commands, Shell Script Basics, Sum of Digits, Date Validation, Palindrome Check, Time-Based Greetings, File Existence Check',
        "Process Management — C Program for Child Process Creation (fork), FCFS Algorithm, Round Robin Algorithm, Banker's Algorithm Implementation",
      ],
    },
    {
      name: 'Software Engineering',
      code: '303105253',
      credits: 3,
      type: 'theory',
      units: [
        'Software Process Models — Waterfall, Incremental, Prototype, Spiral, Concurrent Development Model, Agility & Agile Process, XP, Scrum',
        'Software Project Management — Management Spectrum (People/Product/Process/Project), W5HH Principle, Team Management, Scope & Feasibility, Effort Estimation',
        'Risk & Quality Planning — Risk Identification, Assessment & Control, Quality Planning, Project Monitoring, Detailed Scheduling',
        'Requirements Engineering — Problem Recognition, RE Tasks & Processes, Requirements Specification, Use Cases, Functional Specification, Requirements Validation',
        'Structured System Design — Design Concepts & Models, Software Architecture, Architectural Styles & Patterns, Component-Level Design, OO Design',
        'Data-Oriented Analysis & Design — E-R Diagram, Dataflow Model, Control Flow Model, Data Dictionary, DFD & Structure Chart',
        'Coding & Unit Testing — Programming Principles, Coding Standards, Incremental Development, Unit Testing (Procedural Units & Classes), Code Inspection',
        'Software Metrics — Size Measure, Complexity Metrics, Cyclomatic Complexity, Halstead Measure, Knot Count, Metric Comparison',
        'Software Testing & QA — Testing Psychology, Levels of Testing, Test Plan, Black-Box Testing, White-Box Testing, QA Standards (ISO 9000 & 9001)',
        'Advanced SE — CASE Tools, SCRUM, Dependable Systems, Reliability, Safety, Security, Resilience Engineering, Component-Based & Service-Oriented SE',
      ],
    },
    {
      name: 'SE Laboratory',
      code: '303105254',
      credits: 1,
      type: 'lab',
      units: [
        'Project Planning & SRS — Project Definition, Requirements Engineering Process, Software Requirement Specification (SRS), Design Model Identification',
        'SPMP & Estimation — Software Project Management Plan (SPMP), COCOMO Cost Estimation, Effort & Schedule Planning',
        'Structural Design — DFD with Data Dictionary, Structure Chart for System Analysis & Design',
        'UML Diagrams — Use Case Diagram with Scenarios, Class Diagram, State Diagram, Collaboration Diagram, Sequence Diagram, Activity Diagram',
        'Testing & Quality — Coding Standards & Walkthrough, Test Cases, Testing Tools Comparison, Security & Quality Aspects',
      ],
    },
    {
      name: 'Computer Network',
      code: '303105255',
      credits: 3,
      type: 'theory',
      units: [
        'Data Communication Components — Data Representation, Network Topologies, OSI Model, Protocols & Standards, Transmission Media, LAN (Wired & Wireless), VLAN, Multiplexing (FDM/TDM/WDM), Spread Spectrum',
        'Data Link Layer — Error Detection & Correction (Hamming Distance, CRC, Block Coding), Flow Control, ARQ Protocols (Stop-and-Wait, Go-Back-N, Selective Repeat), Sliding Window, Piggybacking',
        'Medium Access Sub-Layer — Random Access, Pure ALOHA, Slotted ALOHA, CSMA/CD, CDMA/CA',
        'Network Layer — Switching, Logical Addressing (IPv4 & IPv6), Address Mapping (ARP, RARP, BOOTP, DHCP), Delivery, Forwarding & Unicast Routing Protocols',
        'Transport Layer — Process-to-Process Communication, UDP, TCP, SCTP, Congestion Control, QoS, Leaky Bucket & Token Bucket Algorithm',
        'Application Layer — DNS, DDNS, TELNET, EMAIL, FTP, WWW, HTTP, SNMP, Bluetooth, Firewalls, Basic Concepts of Cryptography',
      ],
    },
    {
      name: 'CN Laboratory',
      code: '303105256',
      credits: 1,
      type: 'lab',
      units: [
        'Simulation Tools — Cisco Packet Tracer (Network Device Behaviour), Wireshark (Packet Capture)',
        'LAN Configuration — Data Link Layer Error Correction, Virtual LAN, Wireless LAN',
        'Inter-Networking — Router Experiments (Same Subnet & Cross-Subnet), Subnetting Implementation, Routing at Network Layer, Transport Layer Experiments',
      ],
    },
    {
      name: 'Python & Full Stack Development',
      code: '303105257',
      credits: 3,
      type: 'theory',
      units: [
        'Introduction to Python — Variables, Data Types, Conditional Statements, Loops, Lists, Sets, Tuples, Dictionaries, Common Operations & Built-in Functions',
        'Functions, OOP & Exception Handling — Defining Functions, Arguments, Return Values, OOP Concepts (Class/Object/Encapsulation/Polymorphism/Inheritance), File Handling',
        'Modules, Packages & DB Connectivity — Python Modules & Packages, Popular Libraries, Git Integration with PyCharm, PyTests, MySQL & MongoDB CRUD Operations',
        'Flask Framework — Routing, App Settings, URL Building, HTTP Methods, Templates, Static & Media Files, Form Data, DB Connectivity (SQLite3/MySQL), Flask-Login, Deployment',
        'Django Framework — Project Installation, App Structure, Admin Console, Views, URL Mapping, Template System, Models, Form Processing, Static & Media Files, Deployment',
        'RESTful APIs — REST Architectural Style, HTTP Protocol Role, RESTful API Design, GET/POST/PUT/DELETE, URL & Resource Representations, Status Codes, Versioning, FastAPI/Flask',
      ],
    },
    {
      name: 'Python Full Stack Laboratory',
      code: '303105258',
      credits: 1,
      type: 'lab',
      units: [
        'Python Basics — Temperature Converter, Area Calculator, Random Password Generator, Average Calculator, Leap Year Check, Factorial, Palindrome, Sorting, Multiplication Table, Base Conversion',
        'OOP & File Handling — Bank Account Model, School Management System, Text File Word Count, CSV Average Calculator, Excel Data Reader',
        'Web Application Development — Simple Web Server, User Registration & Login, File Upload/Download, Database Display, User Input Processing, Template Engine, AJAX Support, Django Auth, Third-Party API Integration',
        'RESTful API Development — Simple API (Users JSON), CRUD Resource API, JWT Authentication API, Paginated API, API with Data Validation & Error Handling',
      ],
    },
    {
      name: 'Competitive Coding',
      code: '303105259',
      credits: 2,
      type: 'lab',
      units: [
        'Stacks — MINSTACK (push/pop/min), Expression Evaluation (Postfix/Prefix Notation), LIFO Principle',
        'Queues — Next Greater Element (NGE), Circular Queue (Enqueue/Dequeue/Front/Rear), Shunting Yard Algorithm (Infix to Postfix), Priority Queue (Product of 3 Largest)',
        'Linked Lists — Merge Two Sorted Lists, Find Merge Point, Swap Nodes Pairwise',
        'Trees & BST — Build BST, Validate BST (ISVALID), Tree Depth (MAXDEPTH), Pre/In/Post-Order Traversal, Boundary Traversal, Level Order Traversal, Mirrored Trees, Lowest Common Ancestor (LCA)',
        'Hashing — Basic Hash Function (Key-Value Store), Hash Table with Separate Chaining, Two Sum using HashMap',
        'Tries & Advanced — Trie (Search/Insert/Remove), Huffman Coding, Distinct Substrings, Count Words in Trie, Left View of Tree',
      ],
    },
    {
      name: 'Probability, Statistics & Numerical Methods',
      code: '303191251',
      credits: 4,
      type: 'math',
      units: [
        "Correlation, Regression & Curve Fitting — Correlation & Regression, Rank Correlation, Curve Fitting by Least Squares (Straight Lines, Second Degree Parabola)",
        "Probability & Distributions — Probability Spaces, Conditional Probability, Bayes' Rule, Discrete & Continuous Random Variables, Expectation, Variance, Binomial/Poisson/Normal Distributions",
        'Testing of Hypothesis — Large Sample Tests (Single & Difference of Proportions, Means, Standard Deviations), t-test, F-test (Ratio of Variances), Chi-Square (Goodness of Fit, Independence)',
        'Solution of Linear & Transcendental Equations — Gauss-Jacobi, Gauss-Seidel Methods, Bisection Method, Newton-Raphson Method, Regula-Falsi Method',
        "Finite Differences & Interpolation — Finite Differences, Relation between Operators, Newton's Forward & Backward Difference Formulae, Newton's Divided Differences, Lagrange's Formula",
        "Numerical Integration & ODEs — Trapezoidal Rule, Simpson's 1/3rd & 3/8th Rules, Gaussian Quadrature, Taylor's Series, Euler & Modified Euler's Methods, Runge-Kutta 4th Order",
      ],
    },
    {
      name: 'Professional Grooming & Personality Dev.',
      code: '303193252',
      credits: 1,
      type: 'soft',
      units: [
        'Self Development & Assessment — Change, Grow, Persist, Prioritize, Read, Learn, Listen, Record, Think, Communicate, Relate',
        'Corporate Etiquette — Developing Personality, Telephone Etiquette, Foreign Business Trips, Small Talks, Respecting Privacy, Learning to Say No',
        'Public Speaking — Communicating Information to an Audience, Choosing Pattern, Art of Persuasion, Making Effective Speeches, Delivering Speech Types',
        'Reading & Listening Skills — Reading Activity & Comprehension (Intermediate), Inquiry-Based Listening Practice, Finding Details from Conversations',
        'Resume Writing & Interview Prep — Career Assessments, Mock GD Round, Mock Personal Interview, Employer Expectations, Case Interview',
      ],
    },
  ],
};
